import {
  BarChart3,
  Bell,
  CreditCard,
  Gift,
  QrCode,
  Settings,
  Trophy,
  Users,
  Wallet,
  Image,
  Banknote,
  Megaphone,
  Ticket,
  PanelTop,
  MessageSquare,
  ListOrdered,
  ArrowUpCircle,
  ArrowDownCircle,
  CreditCard as CreditCardAlt,
  Globe,
  Wrench,
  Activity,
  LayoutList,
  FileText,
  RefreshCw,
  BookOpen,
  Target,
  CheckCircle,
  ClipboardList,
} from "lucide-react";

export type NavItem = {
  name: string;
  href?: string;
  icon: React.ComponentType<any>;
  subItems?: { name: string; href: string; icon: React.ComponentType<any> }[];
};

/** Build navigation with the correct panel prefix (e.g. "/admin", "/owner") */
export function getNavigation(prefix: string): NavItem[] {
  return [
    { name: "Dashboard", href: prefix, icon: BarChart3 },
    { name: "Account Statement", href: `${prefix}/account-statement`, icon: BookOpen },
    {
      name: "Result",
      icon: CheckCircle,
      subItems: [
        { name: "Live Prediction", href: `${prefix}/live-prediction`, icon: Target },
        { name: "Sports Result", href: `${prefix}/sports-result`, icon: ClipboardList },
      ],
    },
    {
      name: "Live Markets",
      icon: Activity,
      subItems: [
        { name: "Summary", href: `${prefix}/live-markets/summary`, icon: LayoutList },
        { name: "Details", href: `${prefix}/live-markets/details`, icon: FileText },
      ],
    },
    { name: "Users", href: `${prefix}/users`, icon: Users },
    {
      name: "Sports Games",
      icon: Trophy,
      subItems: [
        { name: "Sports Games", href: `${prefix}/sports-games`, icon: Trophy },
        { name: "Fetch Competitions", href: `${prefix}/fetch-competitions`, icon: RefreshCw },
        { name: "Custom Markets", href: `${prefix}/custom-markets`, icon: Wrench },
      ],
    },
    { name: "Home Sections", href: `${prefix}/home-sections`, icon: Image },
    {
      name: "Marketing",
      icon: Gift,
      subItems: [
        { name: "Promotions", href: `${prefix}/promotions`, icon: Megaphone },
        { name: "Promo Codes", href: `${prefix}/promocodes`, icon: Ticket },
        { name: "Banners", href: `${prefix}/banners`, icon: PanelTop },
        { name: "Popups", href: `${prefix}/popups`, icon: MessageSquare },
      ],
    },
    {
      name: "Vouchers",
      icon: CreditCard,
      subItems: [
        { name: "All Vouchers", href: `${prefix}/vouchers`, icon: ListOrdered },
        { name: "Limit Voucher", href: `${prefix}/vouchers/limit`, icon: CreditCardAlt },
        { name: "Deposit Voucher", href: `${prefix}/vouchers/deposit`, icon: ArrowDownCircle },
        { name: "Withdraw Voucher", href: `${prefix}/vouchers/withdraw`, icon: ArrowUpCircle },
      ],
    },
    { name: "Notifications", href: `${prefix}/notifications`, icon: Bell },
    { name: "QR Codes", href: `${prefix}/qrcodes`, icon: QrCode },
    {
      name: "Withdrawal Methods",
      href: `${prefix}/withdrawal-methods`,
      icon: Wallet,
    },
    { name: "Manage Currency", href: `${prefix}/manage-currency`, icon: Banknote },
    {
      name: "Configuration",
      icon: Settings,
      subItems: [
        { name: "White Labels", href: `${prefix}/whitelabels`, icon: Globe },
        { name: "Settings", href: `${prefix}/settings`, icon: Wrench },
      ],
    },
  ];
}

/** @deprecated Use getNavigation(prefix) instead */
export const navigation = getNavigation("/owner");

export const colorTemplates = [
  {
    name: "Royal Gold",
    theme: {
      background: "#1A1A2E",
      foreground: "#F5F5F5",
      card: "#16213E",
      cardForeground: "#F5F5F5",
      primary: "#D4AF37",
      primaryForeground: "#000000",
      secondary: "#0F3460",
      secondaryForeground: "#F5F5F5",
      muted: "#0F3460",
      mutedForeground: "#C0C0C0",
      accent: "#FFD700",
      accentForeground: "#000000",
      border: "#0F3460",
      input: "#16213E",
      ring: "#D4AF37",
      popover: "#16213E",
      popoverForeground: "#F5F5F5",
      success: "#10B981",
      error: "#DC2626",
      info: "#0EA5E9",
      sidebar: "#1A1A2E",
      sidebarForeground: "#F5F5F5",
      sidebarPrimary: "#D4AF37",
      sidebarPrimaryForeground: "#000000",
      sidebarAccent: "#FFD700",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#0F3460",
      sidebarRing: "#D4AF37",
      headerPrimary: "#16213E",
      headerSecondary: "#D4AF37",
      headerText: "#FFFFFF",
      radius: "0.5rem",
      fontFamily: "Inter, sans-serif",
    },
  },
  {
    name: "Vegas Red",
    theme: {
      background: "#1F1F1F",
      foreground: "#FFFFFF",
      card: "#2D2D2D",
      cardForeground: "#FFFFFF",
      primary: "#DC2626",
      primaryForeground: "#FFFFFF",
      secondary: "#3A3A3A",
      secondaryForeground: "#FFFFFF",
      muted: "#3A3A3A",
      mutedForeground: "#D1D5DB",
      accent: "#F87171",
      accentForeground: "#000000",
      border: "#3A3A3A",
      input: "#2D2D2D",
      ring: "#DC2626",
      popover: "#2D2D2D",
      popoverForeground: "#FFFFFF",
      success: "#10B981",
      error: "#DC2626",
      info: "#0EA5E9",
      sidebar: "#1F1F1F",
      sidebarForeground: "#FFFFFF",
      sidebarPrimary: "#DC2626",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#F87171",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#3A3A3A",
      sidebarRing: "#DC2626",
      headerPrimary: "#1F1F1F",
      headerSecondary: "#DC2626",
      headerText: "#FFFFFF",
      radius: "0.5rem",
      fontFamily: "Inter, sans-serif",
    },
  },
  {
    name: "Emerald Night",
    theme: {
      background: "#0F172A",
      foreground: "#F8FAFC",
      card: "#1E293B",
      cardForeground: "#F8FAFC",
      primary: "#10B981",
      primaryForeground: "#000000",
      secondary: "#334155",
      secondaryForeground: "#F8FAFC",
      muted: "#334155",
      mutedForeground: "#CBD5E1",
      accent: "#6EE7B7",
      accentForeground: "#000000",
      border: "#334155",
      input: "#1E293B",
      ring: "#10B981",
      popover: "#1E293B",
      popoverForeground: "#F8FAFC",
      success: "#10B981",
      error: "#DC2626",
      info: "#0EA5E9",
      sidebar: "#0F172A",
      sidebarForeground: "#F8FAFC",
      sidebarPrimary: "#10B981",
      sidebarPrimaryForeground: "#000000",
      sidebarAccent: "#6EE7B7",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#334155",
      sidebarRing: "#10B981",
      headerPrimary: "#0F172A",
      headerSecondary: "#10B981",
      headerText: "#FFFFFF",
      radius: "0.5rem",
      fontFamily: "Inter, sans-serif",
    },
  },
  {
    name: "Purple Luxury",
    theme: {
      background: "#1E1B4B",
      foreground: "#F3F4F6",
      card: "#312E81",
      cardForeground: "#F3F4F6",
      primary: "#7C3AED",
      primaryForeground: "#FFFFFF",
      secondary: "#3730A3",
      secondaryForeground: "#F3F4F6",
      muted: "#3730A3",
      mutedForeground: "#D1D5DB",
      accent: "#A78BFA",
      accentForeground: "#000000",
      border: "#3730A3",
      input: "#312E81",
      ring: "#7C3AED",
      popover: "#312E81",
      popoverForeground: "#F3F4F6",
      success: "#10B981",
      error: "#DC2626",
      info: "#0EA5E9",
      sidebar: "#1E1B4B",
      sidebarForeground: "#F3F4F6",
      sidebarPrimary: "#7C3AED",
      sidebarPrimaryForeground: "#FFFFFF",
      sidebarAccent: "#A78BFA",
      sidebarAccentForeground: "#000000",
      sidebarBorder: "#3730A3",
      sidebarRing: "#7C3AED",
      headerPrimary: "#1E1B4B",
      headerSecondary: "#7C3AED",
      headerText: "#FFFFFF",
      radius: "0.5rem",
      fontFamily: "Inter, sans-serif",
    },
  },
];
